In [1]:
# Initialize Otter
import otter
grader = otter.Notebook("pandasIntro.ipynb")

## Lecture Section

We will practice working with different Python libraries, packages, and modules in the next several lectures. It is impossible to teach every function, class, and tool available to you from all that we will cover. Instead, we will focus on the most important, common, and useful aspects. The documentation for the library/package/module and other resources will be shared at the end of each lecture.

In this lecture, we will cover:
* The differences between libraries, packages, and modules.
* `pandas` library, including:
    * Series & DataFrames
    * Reading data into a DataFrame
    * Gaining basic information from a dataset

### Libraries vs. Package vs. Module

Before we dig in, let's talk about the difference between a module, package, and library.

* **Modules** are `.py` files that contain functions, classes, and other code.
* **Packages** are collections of modules.
* **Libraries** are collections of packages.

In Python, **library** and **package** are often used interchangeably. You can make your own, but we will only be working with packages already available to you. We will also work with a few modules. The packages we will use are kept up to date by the package owner, and they are all documented online. The modules come built-in to your Python install.

### pandas

pandas is an open-source library for data analysis and manipulation in Python. To use it, we need to `import` it. To save some time, we will import pandas with the alias **pd**

In [2]:
import pandas as pd

There are two important data structures that are specific to pandas: series and dataframe.

**Series:** are similar to columns in a table. They are structured like a Python list, and they can have a header (column-name). They also have an index, like the line numbers in Excel. We can change the indexing, too.

**Dataframes** are created from series. They are the most common data-structure you will see. They create a matrix/table of series.

In [3]:
a = [1, 2, 3, 4]
pd_series = pd.Series(a)
pd_series

0    1
1    2
2    3
3    4
dtype: int64

We can change the indexing with the `index` argument, and we can change the column name with `name`.

In [4]:
pd_series = pd.Series(a, index=["a", "b", "c", "d"], name = "column1")
pd_series

a    1
b    2
c    3
d    4
Name: column1, dtype: int64

If we want to access a specific value at a specific index, we would just index into the series like we would a dictionary (or list).

In [5]:
pd_series['c']

np.int64(3)

To create a dataframe, we use `{}` to create a dictionary object. The keys are the name of the columns, and the lists that follow hold the data for the respective column.

To convert to a pandas DataFrame object, we use `pd.DataFrame()` and we pass our dictionary as the argument.

In [6]:
data_ex = {
  "mph": [70, 85.3, 65.5],
  "duration": [50, 40, 45],
    "vehicle": ["car", "truck", "bus"]
}

dataframe_ex = pd.DataFrame(data_ex)

dataframe_ex

    mph  duration vehicle
0  70.0        50     car
1  85.3        40   truck
2  65.5        45     bus

Dataframes need to have the same number of rows for each column. If data is missing, use `None`. It will be converted to `NaN` in the Dataframe.

In [7]:
data_ex2 = {
  "mph": [70, 85.3, 65.5],
  "duration": [50, None, 45],
    "vehicle": ["car", "truck", "bus"]
}

dataframe_ex2 = pd.DataFrame(data_ex2)

dataframe_ex2

    mph  duration vehicle
0  70.0      50.0     car
1  85.3       NaN   truck
2  65.5      45.0     bus

We can use `.loc[]` to return a row of data as a Series. Don't use `.loc()` - it will return the memory location of the object.

In [8]:
dataframe_ex.loc[1]

mph          85.3
duration       40
vehicle     truck
Name: 1, dtype: object

In [9]:
dataframe_ex.loc[[0, 1]] # a range of rows

    mph  duration vehicle
0  70.0        50     car
1  85.3        40   truck

In [10]:
dataframe_ex.loc[1, "vehicle"] # the rows & specific column

'truck'

We can change indexes in Dataframes, too.

In [11]:
dataframe_ex3 = pd.DataFrame(data_ex2, index=["a", "b", "c"])
dataframe_ex3

    mph  duration vehicle
a  70.0      50.0     car
b  85.3       NaN   truck
c  65.5      45.0     bus

In [12]:
dataframe_ex3.loc['b'] # .loc[] again!

mph          85.3
duration      NaN
vehicle     truck
Name: b, dtype: object

Possibly the most useful aspect of Pandas is its ability to read a file into a DataFrame object.

In [13]:
df = pd.read_csv('data/disney_princess_popularity_dataset_300_rows.csv')
df

,PrincessName,FirstMovieTitle,FirstMovieYear,MovieRuntimeMinutes,NumberOfSongs,HasSoloSong,HasDuet,HairColor,EyeColor,OutfitPrimaryColor,...,RottenTomatoesScore,BoxOfficeMillions,AvgScreenTimeMinutes,NumMerchItemsOnAmazon,GoogleSearchIndex2024,InstagramFanPages,TikTokHashtagViewsMillions,Top3Hashtags,IsIconic,PopularityScore
0,Pocahontas,Pocahontas's Adventure,1977,85,4,No,Yes,Brown,Green,Pink,...,88,661,25,2524,68,298,481,#TeamPocahontas #LovePocahontas #PocahontasFor...,Yes,88
1,Mulan,Mulan's Adventure,1995,85,1,Yes,Yes,Blonde,Brown,Purple,...,91,688,52,4202,49,133,619,#TeamMulan #LoveMulan #MulanForever,Yes,78
2,Raya,Raya's Adventure,1989,110,4,No,No,Blonde,Hazel,Pink,...,76,790,54,525,68,129,230,#TeamRaya #LoveRaya #RayaForever,No,53
3,Anna,Anna's Adventure,1940,78,1,No,No,Brown,Grey,Green,...,70,820,42,1951,73,138,697,#TeamAnna #LoveAnna #AnnaForever,Yes,84
4,Mulan,Mulan's Adventure,1943,103,7,No,Yes,White,Brown,Green,...,86,996,55,3958,34,155,200,#TeamMulan #LoveMulan #MulanForever,Yes,71
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,Merida,Merida's Adventure,2001,95,7,Yes,No,Red,Grey,Purple,...,89,309,49,3638,98,225,881,#TeamMerida #LoveMerida #MeridaForever,No,95
296,Belle,Belle's Adventure,2006,76,1,Yes,No,Red,Green,Yellow,...,97,406,53,1558,33,270,274,#TeamBelle #LoveBelle #BelleForever,No,96
297,Anna,Anna's Adventure,2020,70,2,No,Yes,White,Blue,Blue,...,72,935,25,1815,53,53,164,#TeamAnna #LoveAnna #AnnaForever,Yes,67
298,Tiana,Tiana's Adventure,1937,71,7,No,No,Red,Blue,Purple,...,86,463,54,2365,35,116,584,#TeamTiana #LoveTiana #TianaForever,No,76
299,Mulan,Mulan's Adventure,1938,105,3,No,No,Brown,Brown,Purple,...,77,195,42,2218,89,11,540,#TeamMulan #LoveMulan #MulanForever,No,69

We can use `.head()` and `.tail()` to get the first or last 5 rows of the dataset, respectively. If we pass an integer as an argument, it will return that many rows instead.

In [14]:
df.head()

,PrincessName,FirstMovieTitle,FirstMovieYear,MovieRuntimeMinutes,NumberOfSongs,HasSoloSong,HasDuet,HairColor,EyeColor,OutfitPrimaryColor,...,RottenTomatoesScore,BoxOfficeMillions,AvgScreenTimeMinutes,NumMerchItemsOnAmazon,GoogleSearchIndex2024,InstagramFanPages,TikTokHashtagViewsMillions,Top3Hashtags,IsIconic,PopularityScore
0,Pocahontas,Pocahontas's Adventure,1977,85,4,No,Yes,Brown,Green,Pink,...,88,661,25,2524,68,298,481,#TeamPocahontas #LovePocahontas #PocahontasFor...,Yes,88
1,Mulan,Mulan's Adventure,1995,85,1,Yes,Yes,Blonde,Brown,Purple,...,91,688,52,4202,49,133,619,#TeamMulan #LoveMulan #MulanForever,Yes,78
2,Raya,Raya's Adventure,1989,110,4,No,No,Blonde,Hazel,Pink,...,76,790,54,525,68,129,230,#TeamRaya #LoveRaya #RayaForever,No,53
3,Anna,Anna's Adventure,1940,78,1,No,No,Brown,Grey,Green,...,70,820,42,1951,73,138,697,#TeamAnna #LoveAnna #AnnaForever,Yes,84
4,Mulan,Mulan's Adventure,1943,103,7,No,Yes,White,Brown,Green,...,86,996,55,3958,34,155,200,#TeamMulan #LoveMulan #MulanForever,Yes,71

In [15]:
df.tail(3)

,PrincessName,FirstMovieTitle,FirstMovieYear,MovieRuntimeMinutes,NumberOfSongs,HasSoloSong,HasDuet,HairColor,EyeColor,OutfitPrimaryColor,...,RottenTomatoesScore,BoxOfficeMillions,AvgScreenTimeMinutes,NumMerchItemsOnAmazon,GoogleSearchIndex2024,InstagramFanPages,TikTokHashtagViewsMillions,Top3Hashtags,IsIconic,PopularityScore
297,Anna,Anna's Adventure,2020,70,2,No,Yes,White,Blue,Blue,...,72,935,25,1815,53,53,164,#TeamAnna #LoveAnna #AnnaForever,Yes,67
298,Tiana,Tiana's Adventure,1937,71,7,No,No,Red,Blue,Purple,...,86,463,54,2365,35,116,584,#TeamTiana #LoveTiana #TianaForever,No,76
299,Mulan,Mulan's Adventure,1938,105,3,No,No,Brown,Brown,Purple,...,77,195,42,2218,89,11,540,#TeamMulan #LoveMulan #MulanForever,No,69

Finally, we can gather basic information of our dataset by calling `.info()`.

It shows:
* The number of entries, and the range of the indexes.
* The columns and their index, name, number of non-None (NULL/Nan) values, and type.
* The count of the types
* The memory usage

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 36 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   PrincessName                300 non-null    str
 1   FirstMovieTitle             300 non-null    str
 2   FirstMovieYear              300 non-null    int64
 3   MovieRuntimeMinutes         300 non-null    int64
 4   NumberOfSongs               300 non-null    int64
 5   HasSoloSong                 300 non-null    str
 6   HasDuet                     300 non-null    str
 7   HairColor                   300 non-null    str
 8   EyeColor                    300 non-null    str
 9   OutfitPrimaryColor          300 non-null    str
 10  OutfitStyleEra              300 non-null    str
 11  IsRoyalByBirth              300 non-null    str
 12  HasAnimalSidekick           300 non-null    str
 13  SidekickType                230 non-null    str
 14  HasMagicalPowers            300 non-null    str
 15  MagicType                   247 non-null    str
 16  MainSetting                 300 non-null    str
 17  IsBasedOnRealStory          300 non-null    str
 18  CulturalOrigin              300 non-null    str
 19  SpeaksToAnimals             300 non-null    str
 20  FightsVillainDirectly       300 non-null    str
 21  RomanticSubplot             300 non-null    str
 22  MarriedByEnd                300 non-null    str
 23  VillainName                 300 non-null    str
 24  VillainType                 253 non-null    str
 25  IMDB_Rating                 300 non-null    float64
 26  RottenTomatoesScore         300 non-null    int64
 27  BoxOfficeMillions           300 non-null    int64
 28  AvgScreenTimeMinutes        300 non-null    int64
 29  NumMerchItemsOnAmazon       300 non-null    int64
 30  GoogleSearchIndex2024       300 non-null    int64
 31  InstagramFanPages           300 non-null    int64
 32  TikTokHashtagViewsMillions  300 non-null    int64
 33  Top3Hashtags                300 non-null    str
 34  IsIconic                    300 non-null    str
 35  PopularityScore             300 non-null    int64
dtypes: float64(1), int64(11), str(24)
memory usage: 84.5 KB

## Assignment Section

**Question 1.**

For this problem, you are going to create a `pandas` dataframe called `data_ex`. It needs to have a `sales` (float), `quarter` (int), and `item` (string) column. There should be an equal number of data in each column, and there should at least 5 rows.

In [21]:
import pandas as pd
data = {
  "sales": [100.50, 500.70, 200.00, 300.90, 700.50],
  "quarter": [1, 3, 4, 2, 1],
    "item": ["dress", "skirt", "trousers", "t-shirt", "jeans"]
}

data_ex = pd.DataFrame(data)

data_ex

   sales  quarter      item
0  100.5        1     dress
1  500.7        3     skirt
2  200.0        4  trousers
3  300.9        2   t-shirt
4  700.5        1     jeans

In [22]:
grader.check("q1")

q1 results: All test cases passed!

**Question 2.**

We will borrow a dataset from Kaggle for this exercise. I have edited it for the purposes of this course.
https://www.kaggle.com/datasets/msjahid/colorado-motor-vehicle-sales-data

For this problem, you will use `pandas` to read the `"data/colorado_motor_vehicle_sales.csv"` file. Find the basic info of the dataframe, then fill in the variables with the appropriate response.

* `rows =` : give the number of rows
* `null_sales =` : give the number of null rows in the sales column
* `columns =` : give the number of columns
* `year =` : give the data-type of the column `year` (as a string or as the type object)

In [23]:
df = pd.read_csv("data/colorado_motor_vehicle_sales.csv")

rows = df.shape[0]
null_sales = df['sales'].isna().sum()
columns = df.shape[1]
year = df['year'].dtype

In [24]:
grader.check("q2")

q2 results: All test cases passed!

**Question 3.** Using the dataframe you created in Question 2, create a new dataframe that consists of the old dataframe's first 5 and last 5 rows. Set `ignore_index=True` if using `.concat()`. Do not hard-code the answer.

In [40]:
import pandas as pd
new_df = pd.concat([df.iloc[:5], df.iloc[-3:]], ignore_index = True)
new_df

   year  quarter              county        sales
0  2008        1               Adams  231609000.0
1  2008        1            Arapahoe  550378000.0
2  2008        1  Boulder/Broomfield  176771000.0
3  2008        1              Denver  200103000.0
4  2008        1             Douglas   93259000.0
5  2015        4              Pueblo   94606000.0
6  2015        4       Rest of State  157059000.0
7  2015        4                Weld  192583000.0

In [39]:
df3 = pd.read_csv('data/first_last.csv')
df3

   year  quarter              county        sales
0  2008        1               Adams  231609000.0
1  2008        1            Arapahoe  550378000.0
2  2008        1  Boulder/Broomfield  176771000.0
3  2008        1              Denver  200103000.0
4  2008        1             Douglas   93259000.0
5  2015        4              Pueblo   94606000.0
6  2015        4       Rest of State  157059000.0
7  2015        4                Weld  192583000.0

In [41]:
grader.check("q3")

q3 results: All test cases passed!

---

To double-check your work, the cell below will rerun all of the autograder tests.

In [42]:
grader.check_all()

q1 results: All test cases passed!

q2 results: All test cases passed!

q3 results: All test cases passed!